import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';

const templateFields: Record<string, { name: string; label: string; type: string }[]> = {
  'rent-agreement': [
    { name: 'place', label: 'Place', type: 'text' },
    { name: 'day', label: 'Day', type: 'text' },
    { name: 'month', label: 'Month', type: 'text' },
    { name: 'year', label: 'Year', type: 'text' },
    { name: 'lessorName', label: 'Lessor Name', type: 'text' },
    { name: 'lessorAddress', label: 'Lessor Address', type: 'text' },
    { name: 'lesseeName', label: 'Lessee Name', type: 'text' },
    { name: 'lesseeAddress', label: 'Lessee Address', type: 'text' },
    { name: 'leaseYears', label: 'Lease Years', type: 'text' },
    { name: 'propertyAddress', label: 'Property Address', type: 'text' },
    { name: 'startMonth', label: 'Lease Start Month', type: 'text' },
    { name: 'startYear', label: 'Lease Start Year', type: 'text' },
    { name: 'rentAmount', label: 'Monthly Rent Amount (Rs)', type: 'text' },
    { name: 'rentDueDay', label: 'Rent Due Day (of month)', type: 'text' },
    { name: 'firstRentDate', label: 'First Rent Due Date', type: 'text' },
    { name: 'taxes', label: 'Taxes (Rs)', type: 'text' },
    { name: 'arrearsMonths', label: 'Arrears Months', type: 'text' },
    { name: 'noticePeriod', label: 'Notice Period (months)', type: 'text' },
    { name: 'lessorName', label: 'Lessor Name', type: 'text' },
    { name: 'lesseeName', label: 'Lessee Name', type: 'text' },
    { name: 'Witness1', label: 'Witness1 Name', type: 'text' },
    { name: 'Witness2', label: 'Witness2 Name', type: 'text' },

  ],

  'loan-agreement': [
    { name: 'lenderName', label: 'Lender Name', type: 'text' },
    { name: 'borrowerName', label: 'Borrower Name', type: 'text' },
    { name: 'place', label: 'Place', type: 'text' },
    { name: 'day', label: 'Day', type: 'text' },
    { name: 'month', label: 'Month', type: 'text' },
    { name: 'year', label: 'Year', type: 'text' },
    { name: 'loanAmount', label: 'Loan Amount (Rs)', type: 'text' },
    { name: 'loanAmountWords', label: 'Loan Amount (in words)', type: 'text' },
    { name: 'loanYears', label: 'Loan Period (years)', type: 'text' },
    { name: 'loanStartDate', label: 'Loan Start Date (dd/mm/yyyy)', type: 'text' },
    { name: 'loanEndDate', label: 'Loan End Date (dd/mm/yyyy)', type: 'text' },
    { name: 'loanAmountRepeat', label: 'Loan Amount (Repeat)', type: 'text' },
    { name: 'loanAmountWordsRepeat', label: 'Loan Amount (in words, Repeat)', type: 'text' },
    { name: 'loanYearsRepeat', label: 'Loan Period (years, Repeat)', type: 'text' },
    { name: 'lenderWitness', label: 'Lender Witness Name', type: 'text' },
    { name: 'borrowerWitness', label: 'Borrower Witness Name', type: 'text' },
  ],

  'loan-agreement-security': [
    { name: 'agreementPlace', label: 'Agreement Place', type: 'text' },
    { name: 'agreementDay', label: 'Agreement Day', type: 'text' },
    { name: 'agreementMonth', label: 'Agreement Month', type: 'text' },
    { name: 'agreementYear', label: 'Agreement Year', type: 'text' },
    { name: 'lenderCompany', label: 'Lender Company Name', type: 'text' },
    { name: 'lenderAddress', label: 'Lender Registered Office Address', type: 'text' },
    { name: 'borrowerCompany', label: 'Borrower Company Name', type: 'text' },
    { name: 'borrowerAddress', label: 'Borrower Registered Office Address', type: 'text' },
    { name: 'pledgerCompany', label: 'Pledger Company Name', type: 'text' },
    { name: 'pledgerAddress', label: 'Pledger Registered Office Address', type: 'text' },
    { name: 'borrowerPaidUpCapital', label: 'Borrower Paid Up Capital (Rs. in lacs)', type: 'text' },
    { name: 'paidUpCapitalDate', label: 'Paid Up Capital Date', type: 'text' },
    { name: 'loanAmount', label: 'Loan Amount (Rs)', type: 'text' },
    { name: 'loanAmountWords', label: 'Loan Amount (in words)', type: 'text' },
    { name: 'loanPeriodDays', label: 'Loan Period (days)', type: 'text' },
    { name: 'loanDisbursalDate', label: 'Loan Disbursal Date', type: 'text' },
    { name: 'interestRate', label: 'Interest Rate (%)', type: 'text' },
    { name: 'interestRests', label: 'Interest Rests', type: 'text' },
    { name: 'penalInterestRate', label: 'Penal Interest Rate (%)', type: 'text' },
    { name: 'pledgeAnnexureDetails', label: 'Pledge Annexure Details', type: 'text' },
    { name: 'stockExchange', label: 'Stock Exchange', type: 'text' },
    { name: 'shareMarketPrice', label: 'Share Market Price (Rs)', type: 'text' },
    { name: 'marginPercent', label: 'Margin Percent (%)', type: 'text' },
    { name: 'downwardMarginPercent', label: 'Downward Margin Percent (%)', type: 'text' },
    { name: 'numberOfShares', label: 'Number of Shares', type: 'text' },
    { name: 'borrowerWitness', label: 'Borrower Witness Name', type: 'text' },
    { name: 'pledgerWitness', label: 'Pledger Witness Name', type: 'text' },
    { name: 'lenderWitness', label: 'Lender Witness Name', type: 'text' },
  ],

  'cheque-bounce-notice': [
    { name: 'noticeDate', label: 'Notice Date', type: 'text' },
    { name: 'partyName', label: 'Party Name', type: 'text' },
    { name: 'partyAddress', label: 'Party Address', type: 'text' },
    { name: 'partyContact', label: 'Party Contact Info', type: 'text' },
    { name: 'clientName', label: 'Client Name', type: 'text' },
    { name: 'clientBusiness', label: 'Client Business', type: 'text' },
    { name: 'clientOffice', label: 'Client Office Address', type: 'text' },
    { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text' },
    { name: 'employeeName', label: 'Employee Name', type: 'text' },
    { name: 'product', label: 'Product', type: 'text' },
    { name: 'purchaseOrderDate', label: 'Purchase Order Date', type: 'text' },
    { name: 'purchaseOrderAmount', label: 'Purchase Order Amount', type: 'text' },
    { name: 'purchaseOrderProduct', label: 'Purchase Order Product', type: 'text' },
    { name: 'deliveryProduct', label: 'Delivered Product', type: 'text' },
    { name: 'deliveryOffice', label: 'Delivery Office Address', type: 'text' },
    { name: 'invoiceNo', label: 'Invoice Number', type: 'text' },
    { name: 'invoiceDate', label: 'Invoice Date', type: 'text' },
    { name: 'chequeNo', label: 'Cheque Number', type: 'text' },
    { name: 'chequeDate', label: 'Cheque Date', type: 'text' },
    { name: 'chequeAmount', label: 'Cheque Amount', type: 'text' },
    { name: 'chequeAmountWords', label: 'Cheque Amount (in words)', type: 'text' },
    { name: 'chequeBank', label: 'Cheque Bank', type: 'text' },
    { name: 'chequePresentedDate', label: 'Cheque Presented Date', type: 'text' },
    { name: 'clientBank', label: 'Client Bank', type: 'text' },
    { name: 'chequeReturnMemoDate', label: 'Cheque Return Memo Date', type: 'text' },
    { name: 'clientContactPerson', label: 'Client Contact Person', type: 'text' },
    { name: 'dishonestProduct', label: 'Dishonest Product', type: 'text' },
    { name: 'dishonestAmount', label: 'Dishonest Amount', type: 'text' },
    { name: 'demandAmount', label: 'Demand Amount', type: 'text' },
    { name: 'noticeCost', label: 'Notice Cost', type: 'text' },
    { name: 'advocateSignature', label: 'Advocate Signature', type: 'text' },
  ],

  'legal-notice': [
    { name: 'refNo', label: 'Reference Number', type: 'text' },
    { name: 'noticeDate', label: 'Notice Date', type: 'text' },
    { name: 'recipientName', label: 'Recipient Name', type: 'text' },
    { name: 'clientName', label: 'Client Name', type: 'text' },
    { name: 'clientConstitution', label: 'Client Constitution (firm/individual/company)', type: 'text' },
    { name: 'clientRepresentative', label: 'Client Representative', type: 'text' },
    { name: 'clientBusiness', label: 'Client Business', type: 'text' },
    { name: 'clientTrade', label: 'Client Trade', type: 'text' },
    { name: 'principalAmount', label: 'Principal Amount (Rs)', type: 'text' },
    { name: 'interestRate', label: 'Interest Rate (%)', type: 'text' },
    { name: 'interestAmount', label: 'Interest Amount (Rs)', type: 'text' },
    { name: 'totalAmount', label: 'Total Amount (Rs)', type: 'text' },
    { name: 'noticeInterestRate', label: 'Notice Interest Rate (%)', type: 'text' },
    { name: 'noticeFee', label: 'Notice Fee (Rs)', type: 'text' },
    { name: 'advocateSignature', label: 'Advocate Signature', type: 'text' },
  ],

  'simple-money-bond': [
    { name: 'debtorName', label: 'Debtor Name', type: 'text' },
    { name: 'debtorFatherName', label: 'Debtor Father\'s Name', type: 'text' },
    { name: 'debtorAddress', label: 'Debtor Address', type: 'text' },
    { name: 'creditorName', label: 'Creditor Name', type: 'text' },
    { name: 'creditorFatherName', label: 'Creditor Father\'s Name', type: 'text' },
    { name: 'creditorAddress', label: 'Creditor Address', type: 'text' },
    { name: 'amount', label: 'Amount (Rs)', type: 'text' },
    { name: 'amountWords', label: 'Amount (in words)', type: 'text' },
    { name: 'itemPurchased', label: 'Item Purchased', type: 'text' },
    { name: 'amountRepeat', label: 'Amount (Repeat)', type: 'text' },
    { name: 'interestRate', label: 'Interest Rate (%)', type: 'text' },
    { name: 'date', label: 'Date', type: 'text' },
    { name: 'witness1', label: 'Witness 1 Name', type: 'text' },
    { name: 'witness2', label: 'Witness 2 Name', type: 'text' },
    { name: 'debtorSignature', label: 'Debtor Signature', type: 'text' },
  ],

  'bond-bail-bond': [
    { name: 'personName', label: 'Name of Person', type: 'text' },
    { name: 'personAddress', label: 'Person Address', type: 'text' },
    { name: 'magistrateCourt', label: 'District Magistrate/Court', type: 'text' },
    { name: 'charge', label: 'Charge', type: 'text' },
    { name: 'answerCourt', label: 'Court to Attend', type: 'text' },
    { name: 'answerDay', label: 'Day (to Attend)', type: 'text' },
    { name: 'answerMonth', label: 'Month (to Attend)', type: 'text' },
    { name: 'answerYear', label: 'Year (to Attend)', type: 'text' },
    { name: 'forfeitAmount', label: 'Forfeit Amount (Rs)', type: 'text' },
    { name: 'bondDateDay', label: 'Bond Date - Day', type: 'text' },
    { name: 'bondDateMonth', label: 'Bond Date - Month', type: 'text' },
    { name: 'bondDateYear', label: 'Bond Date - Year', type: 'text' },
    { name: 'personSignature', label: 'Person Signature', type: 'text' },

    { name: 'suretyName', label: 'Surety Name', type: 'text' },
    { name: 'suretyForPerson', label: 'Surety For (Person Name)', type: 'text' },
    { name: 'suretyAddress', label: 'Surety Address', type: 'text' },
    { name: 'suretyCourt', label: 'Surety - Court', type: 'text' },
    { name: 'suretyAnswerCourt', label: 'Surety - Court to Attend', type: 'text' },
    { name: 'suretyAnswerDay', label: 'Surety - Day (to Attend)', type: 'text' },
    { name: 'suretyAnswerMonth', label: 'Surety - Month (to Attend)', type: 'text' },
    { name: 'suretyAnswerYear', label: 'Surety - Year (to Attend)', type: 'text' },
    { name: 'suretyForfeitAmount', label: 'Surety Forfeit Amount (Rs)', type: 'text' },
    { name: 'suretyDateDay', label: 'Surety Date - Day', type: 'text' },
    { name: 'suretyDateMonth', label: 'Surety Date - Month', type: 'text' },
    { name: 'suretyDateYear', label: 'Surety Date - Year', type: 'text' },
    { name: 'suretySignature', label: 'Surety Signature', type: 'text' },
  ],

  'employee-bond-noncompete': [
    { name: 'employeeName', label: 'Employee Name', type: 'text' },
    { name: 'employeeAddress', label: 'Employee Address', type: 'text' },
    { name: 'employerName', label: 'Employer Name', type: 'text' },
    { name: 'bondAmount', label: 'Bond Amount (Rs)', type: 'text' },
    { name: 'employeeQualification', label: 'Employee Qualification', type: 'text' },
    { name: 'factoryProduct', label: 'Factory Product(s)', type: 'text' },
    { name: 'secretType', label: 'Type of Secret/Process', type: 'text' },
    { name: 'compensationAmount', label: 'Compensation Amount (Rs)', type: 'text' },
    { name: 'city', label: 'City (for non-compete)', type: 'text' },
    { name: 'nonCompeteYears', label: 'Non-Compete Period (years)', type: 'text' },
    { name: 'bondDate', label: 'Bond Date', type: 'text' },
    { name: 'witness1', label: 'Witness 1 Name', type: 'text' },
    { name: 'witness2', label: 'Witness 2 Name', type: 'text' },
  ],

  'performance-bond': [
    { name: 'obligorName', label: 'Obligor Name', type: 'text' },
    { name: 'obligorAddress', label: 'Obligor Address', type: 'text' },
    { name: 'obligeeName', label: 'Obligee Name', type: 'text' },
    { name: 'bondAmount', label: 'Bond Amount (Rs)', type: 'text' },
    { name: 'contractDescription', label: 'Contract Description', type: 'text' },
    { name: 'contractLocation', label: 'Contract Location', type: 'text' },
    { name: 'contractAmount', label: 'Contract Amount (Rs)', type: 'text' },
    { name: 'bondDateDay', label: 'Bond Date - Day', type: 'text' },
    { name: 'bondDateMonth', label: 'Bond Date - Month', type: 'text' },
    { name: 'bondDateYear', label: 'Bond Date - Year', type: 'text' },
    { name: 'obligorSignature', label: 'Obligor Signature', type: 'text' },
    { name: 'witness1', label: 'Witness 1 Name', type: 'text' },
    { name: 'witness2', label: 'Witness 2 Name', type: 'text' },
  ],

  'security-bond-surety': [
    { name: 'suretyName', label: 'Surety Name', type: 'text' },
    { name: 'suretyAddress', label: 'Surety Address', type: 'text' },
    { name: 'creditorName', label: 'Creditor Name', type: 'text' },
    { name: 'bondAmount', label: 'Bond Amount (Rs)', type: 'text' },
    { name: 'debtorName', label: 'Debtor Name', type: 'text' },
    { name: 'debtorAddress', label: 'Debtor Address', type: 'text' },
    { name: 'interestRate', label: 'Interest Rate (%)', type: 'text' },
    { name: 'propertyDescription', label: 'Property Description (Schedule)', type: 'text' },
    { name: 'bondAmountRepeat', label: 'Bond Amount (Repeat)', type: 'text' },
    { name: 'interestRateRepeat', label: 'Interest Rate (Repeat)', type: 'text' },
    { name: 'bondAmountFinal', label: 'Bond Amount (Final)', type: 'text' },
    { name: 'propertyRedemption', label: 'Property Redemption Clause', type: 'text' },
    { name: 'bondDate', label: 'Bond Date', type: 'text' },
    { name: 'suretySignature', label: 'Surety Signature', type: 'text' },
    { name: 'witness1', label: 'Witness 1 Name', type: 'text' },
    { name: 'witness2', label: 'Witness 2 Name', type: 'text' },
  ],

  'security-bond-succession': [
    { name: 'principalName', label: 'Principal Name', type: 'text' },
    { name: 'principalFatherName', label: 'Principal Father\'s Name', type: 'text' },
    { name: 'principalAddress', label: 'Principal Address', type: 'text' },
    { name: 'suretyName', label: 'Surety Name', type: 'text' },
    { name: 'suretyFatherName', label: 'Surety Father\'s Name', type: 'text' },
    { name: 'suretyAddress', label: 'Surety Address', type: 'text' },
    { name: 'judgeName', label: 'Judge Name', type: 'text' },
    { name: 'judgeDistrict', label: 'Judge District', type: 'text' },
    { name: 'bondAmount', label: 'Bond Amount (Rs)', type: 'text' },
    { name: 'bondDateDay', label: 'Bond Date - Day', type: 'text' },
    { name: 'bondDateMonth', label: 'Bond Date - Month', type: 'text' },
    { name: 'bondDateYear', label: 'Bond Date - Year', type: 'text' },
    { name: 'bondPlace', label: 'Bond Place', type: 'text' },
    { name: 'adminSignature', label: 'Administration Signature', type: 'text' },
    { name: 'suretySignature', label: 'Surety Signature', type: 'text' },
    { name: 'orderDate', label: 'Order Date', type: 'text' },
    { name: 'deceasedName', label: 'Deceased Name', type: 'text' },
    { name: 'successionAmount', label: 'Succession Amount (Rs)', type: 'text' },
    { name: 'witness1Name', label: 'Witness 1 Name', type: 'text' },
    { name: 'witness1Address', label: 'Witness 1 Address', type: 'text' },
    { name: 'witness1Signature', label: 'Witness 1 Signature', type: 'text' },
    { name: 'witness2Name', label: 'Witness 2 Name', type: 'text' },
    { name: 'witness2Address', label: 'Witness 2 Address', type: 'text' },
    { name: 'witness2Signature', label: 'Witness 2 Signature', type: 'text' },
  ],

  'leave-license-agreement': [
    { name: 'agreementPlace', label: 'Agreement Place', type: 'text' },
    { name: 'agreementDay', label: 'Agreement Day', type: 'text' },
    { name: 'agreementMonth', label: 'Agreement Month', type: 'text' },
    { name: 'agreementYear', label: 'Agreement Year', type: 'text' },
    { name: 'licensorName', label: 'Licensor Name', type: 'text' },
    { name: 'licenseeName', label: 'Licensee Name', type: 'text' },
    { name: 'licenseeAddress', label: 'Licensee Address', type: 'text' },
    { name: 'propertyLocation', label: 'Property Location', type: 'text' },
    { name: 'surveyNo', label: 'Survey Number', type: 'text' },
    { name: 'buildingFloors', label: 'Number of Floors in Building', type: 'text' },
    { name: 'floorNumber', label: 'Floor Number', type: 'text' },
    { name: 'builtUpArea', label: 'Built Up Area (sq ft)', type: 'text' },
    { name: 'requestedFloor', label: 'Requested Floor', type: 'text' },
    { name: 'requestedArea', label: 'Requested Area (sq ft)', type: 'text' },
    { name: 'licenseeBusiness', label: 'Licensee Business', type: 'text' },
    { name: 'licensedFloor', label: 'Licensed Floor', type: 'text' },
    { name: 'licensedArea', label: 'Licensed Area (sq ft)', type: 'text' },
    { name: 'licensePeriod', label: 'License Period (months)', type: 'text' },
    { name: 'licenseStartDate', label: 'License Start Date', type: 'text' },
    { name: 'licenseFee', label: 'License Fee (Rs/month)', type: 'text' },
    { name: 'licenseFeePerSqft', label: 'License Fee per Sq Ft', type: 'text' },
    { name: 'licenseFeeDueDay', label: 'License Fee Due Day', type: 'text' },
    { name: 'licensorWitness', label: 'Licensor Witness Name', type: 'text' },
    { name: 'licenseeWitness', label: 'Licensee Witness Name', type: 'text' },
  ],

  'simple-mortgage-deed': [
    { name: 'deedPlace', label: 'Deed Place', type: 'text' },
    { name: 'deedDay', label: 'Deed Day', type: 'text' },
    { name: 'deedMonth', label: 'Deed Month', type: 'text' },
    { name: 'deedYear', label: 'Deed Year', type: 'text' },
    { name: 'mortgagorName', label: 'Mortgagor Name', type: 'text' },
    { name: 'mortgagorFatherName', label: 'Mortgagor Father\'s Name', type: 'text' },
    { name: 'mortgagorAddress', label: 'Mortgagor Address', type: 'text' },
    { name: 'mortgageeName', label: 'Mortgagee Name', type: 'text' },
    { name: 'mortgageeFatherName', label: 'Mortgagee Father\'s Name', type: 'text' },
    { name: 'mortgageeAddress', label: 'Mortgagee Address', type: 'text' },
    { name: 'propertyMunicipalNo', label: 'Property Municipal Number', type: 'text' },
    { name: 'propertyRoad', label: 'Property Road', type: 'text' },
    { name: 'propertyCity', label: 'Property City', type: 'text' },
    { name: 'propertyDescription', label: 'Property Description', type: 'text' },
    { name: 'loanAmount', label: 'Loan Amount (Rs)', type: 'text' },
    { name: 'repaymentDay', label: 'Repayment Day', type: 'text' },
    { name: 'repaymentMonth', label: 'Repayment Month', type: 'text' },
    { name: 'repaymentYear', label: 'Repayment Year', type: 'text' },
    { name: 'repaymentAmount', label: 'Repayment Amount (Rs)', type: 'text' },
    { name: 'interestRate', label: 'Interest Rate (%)', type: 'text' },
    { name: 'firstInterestDay', label: 'First Interest Installment Day', type: 'text' },
    { name: 'firstInterestMonth', label: 'First Interest Installment Month', type: 'text' },
    { name: 'firstInterestYear', label: 'First Interest Installment Year', type: 'text' },
    { name: 'scheduleDescription', label: 'Schedule Description', type: 'text' },
    { name: 'witness1', label: 'Witness 1 Name', type: 'text' },
    { name: 'witness2', label: 'Witness 2 Name', type: 'text' },
  ],

  'agreement-sale-house': [
    { name: 'agreementPlace', label: 'Agreement Place', type: 'text' },
    { name: 'agreementDay', label: 'Agreement Day', type: 'text' },
    { name: 'agreementMonth', label: 'Agreement Month', type: 'text' },
    { name: 'agreementYear', label: 'Agreement Year', type: 'text' },
    { name: 'vendorName', label: 'Vendor Name', type: 'text' },
    { name: 'vendorFatherName', label: 'Vendor Father\'s Name', type: 'text' },
    { name: 'vendorAddress', label: 'Vendor Address', type: 'text' },
    { name: 'purchaserName', label: 'Purchaser Name', type: 'text' },
    { name: 'purchaserFatherName', label: 'Purchaser Father\'s Name', type: 'text' },
    { name: 'purchaserAddress', label: 'Purchaser Address', type: 'text' },
    { name: 'houseNo', label: 'House Number', type: 'text' },
    { name: 'houseRoad', label: 'House Road', type: 'text' },
    { name: 'houseDescription', label: 'House Description', type: 'text' },
    { name: 'salePrice', label: 'Sale Price (Rs)', type: 'text' },
    { name: 'earnestMoney', label: 'Earnest Money (Rs)', type: 'text' },
    { name: 'earnestMoneyDate', label: 'Earnest Money Date', type: 'text' },
    { name: 'balanceAmount', label: 'Balance Amount (Rs)', type: 'text' },
    { name: 'completionPeriod', label: 'Completion Period (months)', type: 'text' },
    { name: 'advocateReportDays', label: 'Advocate Report Days', type: 'text' },
    { name: 'refundDays', label: 'Refund Days', type: 'text' },
    { name: 'refundInterestDays', label: 'Refund Interest Days', type: 'text' },
    { name: 'refundInterestRate', label: 'Refund Interest Rate (% per month)', type: 'text' },
    { name: 'liquidatedDamages', label: 'Liquidated Damages (Rs)', type: 'text' },
    { name: 'scheduleDescription', label: 'Schedule Description', type: 'text' },
    { name: 'witness1', label: 'Witness 1 Name', type: 'text' },
    { name: 'witness2', label: 'Witness 2 Name', type: 'text' },
  ],

  'independent-contractor-agreement': [
    { name: 'agreementDay', label: 'Agreement Day', type: 'text' },
    { name: 'agreementMonth', label: 'Agreement Month', type: 'text' },
    { name: 'agreementYear', label: 'Agreement Year', type: 'text' },
    { name: 'companyName', label: 'Company Name', type: 'text' },
    { name: 'companyAddress', label: 'Company Address', type: 'text' },
    { name: 'contractorName', label: 'Contractor Name', type: 'text' },
    { name: 'contractorAddress', label: 'Contractor Address', type: 'text' },
    { name: 'dutiesDescription', label: 'Duties Description', type: 'text' },
    { name: 'reportTo', label: 'Report To', type: 'text' },
    { name: 'engagementEndDate', label: 'Engagement End Date', type: 'text' },
    { name: 'compensationType', label: 'Compensation Type (A or B)', type: 'text' },
    { name: 'hourlyRate', label: 'Hourly Rate (if A)', type: 'text' },
    { name: 'maxPayment', label: 'Maximum Payment (if A)', type: 'text' },
    { name: 'lumpSumAmount', label: 'Lump Sum Amount (if B)', type: 'text' },
    { name: 'paymentTerms', label: 'Payment Terms (if B)', type: 'text' },
    { name: 'stateLaw', label: 'Governing State Law', type: 'text' },
    { name: 'arbitrationLocation', label: 'Arbitration Location', type: 'text' },
    { name: 'companySignatory', label: 'Company Signatory', type: 'text' },
    { name: 'companySignatoryTitle', label: 'Company Signatory Title', type: 'text' },
    { name: 'contractorSignatory', label: 'Contractor Signatory', type: 'text' },
    { name: 'contractorSignatoryTitle', label: 'Contractor Signatory Title', type: 'text' },
  ],

  'shareholders-agreement': [
    { name: 'agreementDay', label: 'Agreement Day', type: 'text' },
    { name: 'agreementMonth', label: 'Agreement Month', type: 'text' },
    { name: 'agreementYear', label: 'Agreement Year', type: 'text' },
    { name: 'partyAName', label: 'Party A Name', type: 'text' },
    { name: 'partyAAddress', label: 'Party A Address', type: 'text' },
    { name: 'partyBName', label: 'Party B Name', type: 'text' },
    { name: 'partyBAddress', label: 'Party B Address', type: 'text' },
    { name: 'companyName', label: 'Company Name', type: 'text' },
    { name: 'companyType', label: 'Company Type', type: 'text' },
    { name: 'companyAct', label: 'Companies Act Year', type: 'text' },
    { name: 'companyRegOffice', label: 'Company Registered Office', type: 'text' },
    { name: 'companyRep', label: 'Company Representative', type: 'text' },
    { name: 'companyBusinessDesc', label: 'Business Description', type: 'text' },
    { name: 'companyBusinessAddress', label: 'Business Address', type: 'text' },
    { name: 'companyRegOfficeClause', label: 'Registered Office Clause', type: 'text' },
    { name: 'companyAuthCapital', label: 'Authorised Share Capital (Rs)', type: 'text' },
    { name: 'companyAuthCapitalWords', label: 'Authorised Share Capital (in words)', type: 'text' },
    { name: 'companyEquityShares', label: 'Equity Shares (number)', type: 'text' },
    { name: 'companyEquitySharesWords', label: 'Equity Shares (in words)', type: 'text' },
    { name: 'partyAShares', label: 'A\'s Shares (number)', type: 'text' },
    { name: 'partyASharesWords', label: 'A\'s Shares (in words)', type: 'text' },
    { name: 'partyBShares', label: 'B\'s Shares (number)', type: 'text' },
    { name: 'partyBSharesWords', label: 'B\'s Shares (in words)', type: 'text' },
    { name: 'auditorsName', label: 'Auditors Name', type: 'text' },
    { name: 'registeredBank', label: 'Registered Bank', type: 'text' },
    { name: 'loanAmount', label: 'Loan Amount (Rs)', type: 'text' },
    { name: 'furtherMoneyByB', label: 'Further Money by B (Rs)', type: 'text' },
    { name: 'collateralAmount', label: 'Collateral Amount (Rs)', type: 'text' },
    { name: 'managementCompany', label: 'Management Company', type: 'text' },
    { name: 'profitLimit', label: 'Profit Limit (Rs)', type: 'text' },
    { name: 'profitLimitWords', label: 'Profit Limit (in words)', type: 'text' },
    { name: 'loanRepayBank', label: 'Loan Repay Bank', type: 'text' },
    { name: 'loanRepayAmount', label: 'Loan Repay Amount (Rs)', type: 'text' },
    { name: 'interestRate', label: 'Interest Rate (%)', type: 'text' },
    { name: 'arbitrationVenue', label: 'Arbitration Venue', type: 'text' },
    { name: 'witness1', label: 'Witness 1 Name', type: 'text' },
    { name: 'witness2', label: 'Witness 2 Name', type: 'text' },
    { name: 'witness3', label: 'Witness 3 Name', type: 'text' },
  ],

  'joint-venture-shareholders-agreement': [
    { name: 'agreementPlace', label: 'Agreement Place', type: 'text' },
    { name: 'agreementDate', label: 'Agreement Date', type: 'text' },
    { name: 'abcCompanyName', label: 'ABC Company Name', type: 'text' },
    { name: 'xyzCompanyName', label: 'XYZ Company Name', type: 'text' },
    { name: 'abcBusiness', label: 'ABC Business', type: 'text' },
    { name: 'xyzBusiness', label: 'XYZ Business', type: 'text' },
    { name: 'projectName', label: 'Project Name', type: 'text' },
    { name: 'principalObject', label: 'Principal Object', type: 'text' },
    { name: 'jvCompanyName', label: 'Joint Venture Company Name', type: 'text' },
    { name: 'xyzShare', label: 'XYZ Share (%)', type: 'text' },
    { name: 'abcShare', label: 'ABC Share (%)', type: 'text' },
    { name: 'incorporationState', label: 'Incorporation State', type: 'text' },
    { name: 'regOfficeAddress', label: 'Registered Office Address', type: 'text' },
    { name: 'moaObjects', label: 'MOA Objects', type: 'text' },
    { name: 'authCapital', label: 'Authorised Capital (Rs)', type: 'text' },
    { name: 'authCapitalWords', label: 'Authorised Capital (in words)', type: 'text' },
    { name: 'equityShares', label: 'Number of Equity Shares', type: 'text' },
    { name: 'shareValue', label: 'Share Value (Rs)', type: 'text' },
    { name: 'shareValueWords', label: 'Share Value (in words)', type: 'text' },
    { name: 'abcWitness1', label: 'ABC Witness 1', type: 'text' },
    { name: 'abcWitness2', label: 'ABC Witness 2', type: 'text' },
    { name: 'xyzWitness1', label: 'XYZ Witness 1', type: 'text' },
    { name: 'xyzWitness2', label: 'XYZ Witness 2', type: 'text' },
  ],

  'memorandum-of-understanding': [
    { name: 'mouDateDay', label: 'MOU Day', type: 'text' },
    { name: 'mouDateMonth', label: 'MOU Month', type: 'text' },
    { name: 'abcName', label: 'ABC Name', type: 'text' },
    { name: 'abcOffice', label: 'ABC Office Address', type: 'text' },
    { name: 'xyzName', label: 'XYZ Name', type: 'text' },
    { name: 'xyzOffice', label: 'XYZ Office Address', type: 'text' },
    { name: 'companyName', label: 'Company Name', type: 'text' },
    { name: 'companyBusiness', label: 'Company Business/Portal Type', type: 'text' },
    { name: 'portalName', label: 'Portal Name', type: 'text' },
    { name: 'xyzInvestment', label: 'XYZ Investment Amount (Rs)', type: 'text' },
    { name: 'xyzInvestmentWords', label: 'XYZ Investment Amount (in words)', type: 'text' },
    { name: 'xyzCapitalPercent', label: 'XYZ Capital (%)', type: 'text' },
    { name: 'abcCapitalPercent', label: 'ABC Capital (%)', type: 'text' },
    { name: 'paidUpCapital', label: 'Paid Up Capital (Rs)', type: 'text' },
    { name: 'paidUpCapitalWords', label: 'Paid Up Capital (in words)', type: 'text' },
    { name: 'equityShares', label: 'Number of Equity Shares', type: 'text' },
    { name: 'equitySharesWords', label: 'Number of Equity Shares (in words)', type: 'text' },
    { name: 'shareValue', label: 'Share Value (Rs)', type: 'text' },
    { name: 'shareValueWords', label: 'Share Value (in words)', type: 'text' },
    { name: 'stockOptionsTotal', label: 'Total Stock Options', type: 'text' },
    { name: 'stockOptionsXYZ', label: 'Stock Options to XYZ', type: 'text' },
    { name: 'stockOptionsPQR', label: 'Stock Options to PQR', type: 'text' },
    { name: 'stockOptionsABC', label: 'Stock Options to be allotted by ABC', type: 'text' },
    { name: 'xyzPaymentTotal', label: 'Total Payment by XYZ Group (Rs)', type: 'text' },
    { name: 'xyzPaymentTotalWords', label: 'Total Payment by XYZ Group (in words)', type: 'text' },
    { name: 'xyzPaymentShareCapital', label: 'Share Capital Portion (Rs)', type: 'text' },
    { name: 'xyzPaymentPremium', label: 'Premium Portion (Rs)', type: 'text' },
    { name: 'xyzPaymentReceived', label: 'Amount Already Received (Rs)', type: 'text' },
    { name: 'xyzPaymentReceivedWords', label: 'Amount Already Received (in words)', type: 'text' },
    { name: 'xyzPaymentUSD', label: 'Amount Already Received (USD)', type: 'text' },
    { name: 'xyzPaymentBalance', label: 'Balance Amount (Rs)', type: 'text' },
    { name: 'xyzPaymentBalanceWords', label: 'Balance Amount (in words)', type: 'text' },
    { name: 'xyzPaymentScheduleA', label: 'Payment A (Rs)', type: 'text' },
    { name: 'xyzPaymentScheduleADate', label: 'Payment A Date', type: 'text' },
    { name: 'xyzPaymentScheduleB', label: 'Payment B (Rs)', type: 'text' },
    { name: 'xyzPaymentScheduleBDate', label: 'Payment B Date', type: 'text' },
    { name: 'xyzPaymentScheduleC', label: 'Payment C (Rs)', type: 'text' },
    { name: 'xyzPaymentScheduleCDate', label: 'Payment C Date', type: 'text' },
    { name: 'xyzPaymentScheduleD', label: 'Payment D (Rs)', type: 'text' },
    { name: 'xyzPaymentScheduleDDate', label: 'Payment D Date', type: 'text' },
    { name: 'xyzPaymentScheduleE', label: 'Payment E (Rs)', type: 'text' },
    { name: 'xyzPaymentScheduleEDate', label: 'Payment E Date', type: 'text' },
    { name: 'xyzPaymentScheduleF', label: 'Payment F (Rs)', type: 'text' },
    { name: 'xyzPaymentScheduleFDate', label: 'Payment F Date', type: 'text' },
    { name: 'xyzPaymentScheduleG', label: 'Payment G (Rs)', type: 'text' },
    { name: 'xyzPaymentScheduleGDate', label: 'Payment G Date', type: 'text' },
    { name: 'abcWitness', label: 'ABC Witness', type: 'text' },
    { name: 'xyzWitness', label: 'XYZ Witness', type: 'text' },
  ],

  'franchise-agreement': [
    { name: 'agreementDay', label: 'Agreement Day', type: 'text' },
    { name: 'agreementMonth', label: 'Agreement Month', type: 'text' },
    { name: 'agreementYear', label: 'Agreement Year', type: 'text' },
    { name: 'companyName', label: 'Company Name (XYZ Limited)', type: 'text' },
    { name: 'companyType', label: 'Company Type', type: 'text' },
    { name: 'companyRegOffice', label: 'Company Registered Office', type: 'text' },
    { name: 'companyRepTitle', label: 'Company Rep Title', type: 'text' },
    { name: 'companyRepName', label: 'Company Rep Name', type: 'text' },
    { name: 'agentFirmName', label: 'Agent Firm Name', type: 'text' },
    { name: 'agentBusinessAddress', label: 'Agent Business Address', type: 'text' },
    { name: 'agentRepName', label: 'Agent Rep Name', type: 'text' },
    { name: 'products', label: 'Products', type: 'text' },
    { name: 'tradeName', label: 'Trade Name', type: 'text' },
    { name: 'tradeMark', label: 'Trade Mark', type: 'text' },
    { name: 'promotionProducts', label: 'Promotion Products', type: 'text' },
    { name: 'retailCity', label: 'Retail Outlet City', type: 'text' },
    { name: 'premisesDescription', label: 'Premises Description', type: 'text' },
    { name: 'premisesCost', label: 'Premises Cost', type: 'text' },
    { name: 'premisesCostWords', label: 'Premises Cost (in words)', type: 'text' },
    { name: 'shopName', label: 'Shop Name', type: 'text' },
    { name: 'consignmentProducts', label: 'Consignment Products', type: 'text' },
    { name: 'personnel', label: 'Personnel Details', type: 'text' },
    { name: 'bankGuaranteeAmount', label: 'Bank Guarantee Amount', type: 'text' },
    { name: 'bankGuaranteeAmountWords', label: 'Bank Guarantee Amount (in words)', type: 'text' },
    { name: 'commissionPercent', label: 'Commission Percent', type: 'text' },
    { name: 'commissionDay', label: 'Commission Payment Day', type: 'text' },
    { name: 'agreementDurationYears', label: 'Agreement Duration (years)', type: 'text' },
    { name: 'agreementStartDate', label: 'Agreement Start Date', type: 'text' },
    { name: 'terminationNoticeDays', label: 'Termination Notice (days)', type: 'text' },
    { name: 'securityDepositAmount', label: 'Security Deposit Amount', type: 'text' },
    { name: 'securityDepositAmountWords', label: 'Security Deposit Amount (in words)', type: 'text' },
    { name: 'payOrderNo', label: 'Pay Order Number', type: 'text' },
    { name: 'payOrderDate', label: 'Pay Order Date', type: 'text' },
    { name: 'payOrderBank', label: 'Pay Order Bank', type: 'text' },
    { name: 'payOrderBranch', label: 'Pay Order Branch', type: 'text' },
    { name: 'jurisdictionCity', label: 'Jurisdiction City', type: 'text' },
    { name: 'schedulePremisesNo', label: 'Schedule Premises No.', type: 'text' },
    { name: 'schedulePremisesAddress', label: 'Schedule Premises Address', type: 'text' },
    { name: 'measureEastWest', label: 'Measurement East to West', type: 'text' },
    { name: 'measureNorthSouth', label: 'Measurement North to South', type: 'text' },
    { name: 'boundaryEast', label: 'Boundary East', type: 'text' },
    { name: 'boundaryWest', label: 'Boundary West', type: 'text' },
    { name: 'boundaryNorth', label: 'Boundary North', type: 'text' },
    { name: 'boundarySouth', label: 'Boundary South', type: 'text' },
    { name: 'place', label: 'Place', type: 'text' },
    { name: 'date', label: 'Date', type: 'text' },
    { name: 'witness1', label: 'Witness 1', type: 'text' },
    { name: 'witness2', label: 'Witness 2', type: 'text' },
  ],

  'employee-service-agreement': [
    { name: 'agreementPlace', label: 'Agreement Place', type: 'text' },
    { name: 'agreementDay', label: 'Agreement Day', type: 'text' },
    { name: 'agreementMonth', label: 'Agreement Month', type: 'text' },
    { name: 'employerCompany', label: 'Employer Company Name', type: 'text' },
    { name: 'employerType', label: 'Employer Company Type', type: 'text' },
    { name: 'employerRepTitle', label: 'Employer Representative Title', type: 'text' },
    { name: 'employerRepName', label: 'Employer Representative Name', type: 'text' },
    { name: 'employerRepFather', label: 'Employer Rep Father Name', type: 'text' },
    { name: 'employerRegOffice', label: 'Employer Registered Office', type: 'text' },
    { name: 'employeeName', label: 'Employee Name', type: 'text' },
    { name: 'employeeFather', label: 'Employee Father Name', type: 'text' },
    { name: 'employeeNationality', label: 'Employee Nationality', type: 'text' },
    { name: 'employeeAge', label: 'Employee Age', type: 'text' },
    { name: 'employeeAddress', label: 'Employee Address', type: 'text' },
    { name: 'employerBusiness', label: 'Employer Business', type: 'text' },
    { name: 'postApplied', label: 'Post Applied For', type: 'text' },
    { name: 'applicationDate', label: 'Application Date', type: 'text' },
    { name: 'appointmentPost', label: 'Appointment Post', type: 'text' },
    { name: 'appointedPost', label: 'Appointed Post', type: 'text' },
    { name: 'probationPeriod', label: 'Probation Period', type: 'text' },
    { name: 'employmentDuration', label: 'Employment Duration', type: 'text' },
    { name: 'postingPlace', label: 'Place of Posting', type: 'text' },
    { name: 'reportingDate', label: 'Reporting Date', type: 'text' },
    { name: 'workStartTime', label: 'Work Start Time', type: 'text' },
    { name: 'workEndTime', label: 'Work End Time', type: 'text' },
    { name: 'weeklyHoliday', label: 'Weekly Holiday', type: 'text' },
    { name: 'probationStipend', label: 'Probation Stipend (Rs)', type: 'text' },
    { name: 'basicSalary', label: 'Basic Salary after Probation (Rs)', type: 'text' },
    { name: 'companyPolicy', label: 'Company Policy/Handbook', type: 'text' },
    { name: 'witness1', label: 'Witness 1', type: 'text' },
    { name: 'witness2', label: 'Witness 2', type: 'text' },
  ],

  'confidential-nda': [
    { name: 'abcName', label: 'ABC Name', type: 'text' },
    { name: 'abcOffice', label: 'ABC Office Address', type: 'text' },
    { name: 'defName', label: 'DEF Name', type: 'text' },
    { name: 'defOffice', label: 'DEF Office Address', type: 'text' },
    { name: 'abcSubject', label: 'Subject of ABC Information', type: 'text' },
    { name: 'defSubject', label: 'Subject of DEF Information', type: 'text' },
    { name: 'purpose', label: 'Purpose(s) of Disclosures', type: 'text' },
    { name: 'oralDisclosureDays', label: 'Oral Disclosure Written Notice (days)', type: 'text' },
    { name: 'priorNoticeDays', label: 'Prior Written Notice to Disclose (days)', type: 'text' },
    { name: 'confidentialYears', label: 'Confidentiality Period (years)', type: 'text' },
    { name: 'exportCountry', label: 'Export Country', type: 'text' },
    { name: 'agreementYears', label: 'Agreement Duration (years)', type: 'text' },
    { name: 'governingLaw', label: 'Governing Law (Jurisdiction)', type: 'text' },
    { name: 'abcSignatory', label: 'ABC Signatory Name', type: 'text' },
    { name: 'abcTitle', label: 'ABC Signatory Title', type: 'text' },
    { name: 'abcSignDate', label: 'ABC Signature Date', type: 'text' },
    { name: 'defSignatory', label: 'DEF Signatory Name', type: 'text' },
    { name: 'defTitle', label: 'DEF Signatory Title', type: 'text' },
    { name: 'defSignDate', label: 'DEF Signature Date', type: 'text' },
  ],

  'business-service-agreement': [
    { name: 'agreementPlace', label: 'Agreement Place', type: 'text' },
    { name: 'agreementDay', label: 'Agreement Day', type: 'text' },
    { name: 'agreementMonth', label: 'Agreement Month', type: 'text' },
    { name: 'agreementYear', label: 'Agreement Year', type: 'text' },
    { name: 'centreName', label: 'Centre Name', type: 'text' },
    { name: 'centreAddress', label: 'Centre Address', type: 'text' },
    { name: 'clientName', label: 'Client Name', type: 'text' },
    { name: 'clientIncorporation', label: 'Client Incorporation Details', type: 'text' },
    { name: 'clientRegOffice', label: 'Client Registered Office', type: 'text' },
    { name: 'societyName', label: 'Society Name', type: 'text' },
    { name: 'societyAddress', label: 'Society Address', type: 'text' },
    { name: 'premisesDescription', label: 'Premises Description', type: 'text' },
    { name: 'centreBusinessName', label: 'Centre Business Name', type: 'text' },
    { name: 'centreBusinessAddress', label: 'Centre Business Address', type: 'text' },
    { name: 'clientBusiness', label: 'Client Business', type: 'text' },
    { name: 'officeFacilities', label: 'Office Facilities', type: 'text' },
    { name: 'serviceCharge1', label: 'Service Charge 1 (Rs)', type: 'text' },
    { name: 'serviceCharge1Words', label: 'Service Charge 1 (in words)', type: 'text' },
    { name: 'serviceCharge2', label: 'Service Charge 2 (Rs)', type: 'text' },
    { name: 'serviceCharge2Words', label: 'Service Charge 2 (in words)', type: 'text' },
    { name: 'serviceCharge3', label: 'Service Charge 3 (Rs)', type: 'text' },
    { name: 'serviceCharge3Words', label: 'Service Charge 3 (in words)', type: 'text' },
    { name: 'securityDeposit', label: 'Security Deposit (Rs)', type: 'text' },
    { name: 'securityDepositWords', label: 'Security Deposit (in words)', type: 'text' },
    { name: 'liquidatedDamages', label: 'Liquidated Damages (Rs)', type: 'text' },
    { name: 'liquidatedDamagesWords', label: 'Liquidated Damages (in words)', type: 'text' },
    { name: 'compensationPerDay', label: 'Compensation per Day (Rs)', type: 'text' },
    { name: 'compensationPerDayWords', label: 'Compensation per Day (in words)', type: 'text' },
    { name: 'arbitratorName', label: 'Arbitrator Name', type: 'text' },
    { name: 'arbitratorOffice', label: 'Arbitrator Office Address', type: 'text' },
    { name: 'centreSignatory', label: 'Centre Signatory', type: 'text' },
    { name: 'centreSignatoryTitle', label: 'Centre Signatory Title', type: 'text' },
    { name: 'centreWitness', label: 'Centre Witness', type: 'text' },
    { name: 'clientSignatory', label: 'Client Signatory', type: 'text' },
    { name: 'clientWitness', label: 'Client Witness', type: 'text' },
  ],

  'partnership-agreement': [
    { name: 'agreementPlace', label: 'Agreement Place', type: 'text' },
    { name: 'agreementDay', label: 'Agreement Day', type: 'text' },
    { name: 'agreementMonth', label: 'Agreement Month', type: 'text' },
    { name: 'party1Name', label: 'First Party Name', type: 'text' },
    { name: 'party1Age', label: 'First Party Age', type: 'text' },
    { name: 'party1Father', label: 'First Party Father Name', type: 'text' },
    { name: 'party1Address', label: 'First Party Address', type: 'text' },
    { name: 'party2Name', label: 'Second Party Name', type: 'text' },
    { name: 'party2Age', label: 'Second Party Age', type: 'text' },
    { name: 'party2Father', label: 'Second Party Father Name', type: 'text' },
    { name: 'party2Address', label: 'Second Party Address', type: 'text' },
    { name: 'party3Name', label: 'Third Party Name', type: 'text' },
    { name: 'party3Age', label: 'Third Party Age', type: 'text' },
    { name: 'party3Father', label: 'Third Party Father Name', type: 'text' },
    { name: 'party3Address', label: 'Third Party Address', type: 'text' },
    { name: 'party4Name', label: 'Fourth Party Name', type: 'text' },
    { name: 'party4Age', label: 'Fourth Party Age', type: 'text' },
    { name: 'party4Father', label: 'Fourth Party Father Name', type: 'text' },
    { name: 'party4Address', label: 'Fourth Party Address', type: 'text' },
    { name: 'businessType', label: 'Business Type', type: 'text' },
    { name: 'firmName', label: 'Firm Name', type: 'text' },
    { name: 'firmAddress', label: 'Firm Address', type: 'text' },
    { name: 'oldDeedDate', label: 'Old Partnership Deed Date', type: 'text' },
    { name: 'amendmentEffectiveDate', label: 'Amendment Effective Date', type: 'text' },
    { name: 'partnershipSince', label: 'Partnership Since (date)', type: 'text' },
    { name: 'capitalDate', label: 'Capital Investment Date', type: 'text' },
    { name: 'interestRate', label: 'Interest Rate (%)', type: 'text' },
    { name: 'workingPartners', label: 'Working Partners Names', type: 'text' },
    { name: 'remunerationSection', label: 'Remuneration Section', type: 'text' },
    { name: 'remunerationA', label: 'Remuneration A (Name & %)', type: 'text' },
    { name: 'remunerationB', label: 'Remuneration B (Name & %)', type: 'text' },
    { name: 'remunerationC', label: 'Remuneration C (Name & %)', type: 'text' },
    { name: 'profitShare1', label: 'Profit Share 1 (Name & %)', type: 'text' },
    { name: 'profitShare2', label: 'Profit Share 2 (Name & %)', type: 'text' },
    { name: 'profitShare3', label: 'Profit Share 3 (Name & %)', type: 'text' },
    { name: 'profitShare4', label: 'Profit Share 4 (Name & %)', type: 'text' },
    { name: 'bankOperation', label: 'Bank Operation Details', type: 'text' },
    { name: 'accountClosingDay', label: 'Account Closing Day', type: 'text' },
    { name: 'successionClause', label: 'Succession Clause', type: 'text' },
    { name: 'admissionClause', label: 'Admission of New Partners Clause', type: 'text' },
    { name: 'partnerCapacity', label: 'Partner Capacity', type: 'text' },
    { name: 'arbitrationPlace', label: 'Arbitration Place', type: 'text' },
    { name: 'witness1', label: 'Witness 1', type: 'text' },
    { name: 'witness2', label: 'Witness 2', type: 'text' },
  ],

  'retainership-agreement': [
    { name: 'agreementPlace', label: 'Agreement Place', type: 'text' },
    { name: 'agreementDay', label: 'Agreement Day', type: 'text' },
    { name: 'agreementMonth', label: 'Agreement Month', type: 'text' },
    { name: 'agreementYear', label: 'Agreement Year', type: 'text' },
    { name: 'societyName', label: 'Society Name', type: 'text' },
    { name: 'societyRegOffice', label: 'Society Registered Office', type: 'text' },
    { name: 'abcOffice', label: 'ABC Registered Office', type: 'text' },
    { name: 'monthlyFee', label: 'Monthly Fee (Rs)', type: 'text' },
    { name: 'monthlyFeeWords', label: 'Monthly Fee (in words)', type: 'text' },
    { name: 'societySecretary', label: 'Society Secretary Name', type: 'text' },
    { name: 'societyWitness', label: 'Society Witness', type: 'text' },
    { name: 'abcAuthority', label: 'ABC Concerned Authority', type: 'text' },
    { name: 'abcSignatory', label: 'ABC Signatory Name', type: 'text' },
    { name: 'abcWitness', label: 'ABC Witness', type: 'text' },
  ],

  'deed-of-guarantee': [
    { name: 'executionDay', label: 'Execution Day', type: 'text' },
    { name: 'executionMonth', label: 'Execution Month', type: 'text' },
    { name: 'executionYear', label: 'Execution Year', type: 'text' },
    { name: 'firstPartyName', label: 'First Party Name', type: 'text' },
    { name: 'firstPartyAddress', label: 'First Party Address', type: 'text' },
    { name: 'secondPartyName', label: 'Second Party Name', type: 'text' },
    { name: 'secondPartyAddress', label: 'Second Party Address', type: 'text' },
    { name: 'agreementDate', label: 'Underlying Agreement Date', type: 'text' },
    { name: 'developerName', label: 'Developer Name (M/s.)', type: 'text' },
    { name: 'propertyNo', label: 'Property Number/Description', type: 'text' },
    { name: 'partnerOrDirectorOf', label: 'First Party is Partner/Director of', type: 'text' },
    { name: 'assurancesBy', label: 'Assurances Given By (M/s.)', type: 'text' },
    { name: 'performanceBy', label: 'Performance By (M/s.)', type: 'text' },
    { name: 'guaranteeAmount', label: 'Guarantee Amount', type: 'text' },
    { name: 'guaranteeInterest', label: 'Guarantee Interest/Returns', type: 'text' },
    { name: 'firstPartyPerson', label: 'First Party Person Name', type: 'text' },
    { name: 'noticeDate', label: 'Notice Date', type: 'text' },
    { name: 'firstPartyNoticeAddress', label: 'First Party Notice Address', type: 'text' },
    { name: 'secondPartyNewName', label: 'Second Party New Name (if any)', type: 'text' },
    { name: 'fulfillmentBy', label: 'Fulfillment By (M/s.)', type: 'text' },
    { name: 'additionalSecurityBy', label: 'Additional Security By (M/s.)', type: 'text' },
    { name: 'witness1', label: 'Witness 1', type: 'text' },
    { name: 'witness2', label: 'Witness 2', type: 'text' },
  ],

  'agreement-for-sale': [
    { name: 'agreementDay', label: 'Agreement Day', type: 'text' },
    { name: 'agreementMonth', label: 'Agreement Month', type: 'text' },
    { name: 'agreementYear', label: 'Agreement Year', type: 'text' },
    { name: 'sellerName', label: 'Seller Name', type: 'text' },
    { name: 'sellerFather', label: 'Seller Father\'s Name', type: 'text' },
    { name: 'sellerAge', label: 'Seller Age', type: 'text' },
    { name: 'sellerAddress', label: 'Seller Address', type: 'text' },
    { name: 'purchaserName', label: 'Purchaser Name', type: 'text' },
    { name: 'purchaserFather', label: 'Purchaser Father\'s Name', type: 'text' },
    { name: 'purchaserAge', label: 'Purchaser Age', type: 'text' },
    { name: 'purchaserAddress', label: 'Purchaser Address', type: 'text' },
    { name: 'scheduleProperty', label: 'Schedule Property Description', type: 'text' },
    { name: 'sellerPurchasedFrom', label: 'Seller Purchased From', type: 'text' },
    { name: 'sellerPurchaseDeedDate', label: 'Seller Purchase Deed Date', type: 'text' },
    { name: 'sellerPurchaseDocNo', label: 'Seller Purchase Doc No.', type: 'text' },
    { name: 'sellerPurchaseBook', label: 'Seller Purchase Book/Volume/Page', type: 'text' },
    { name: 'sellerPurchaseRegDate', label: 'Seller Purchase Registration Date', type: 'text' },
    { name: 'purposeOfSale', label: 'Purpose of Sale', type: 'text' },
    { name: 'saleConsideration', label: 'Sale Consideration (Rs)', type: 'text' },
    { name: 'saleConsiderationWords', label: 'Sale Consideration (in words)', type: 'text' },
    { name: 'advanceAmount', label: 'Advance Amount (Rs)', type: 'text' },
    { name: 'advanceAmountWords', label: 'Advance Amount (in words)', type: 'text' },
    { name: 'advancePaymentMode', label: 'Advance Payment Mode (cash/cheque)', type: 'text' },
    { name: 'advanceChequeNo', label: 'Advance Cheque No.', type: 'text' },
    { name: 'advanceChequeBank', label: 'Advance Cheque Bank', type: 'text' },
    { name: 'advanceChequeDate', label: 'Advance Cheque Date', type: 'text' },
    { name: 'balanceAmount', label: 'Balance Amount (Rs)', type: 'text' },
    { name: 'balanceAmountWords', label: 'Balance Amount (in words)', type: 'text' },
    { name: 'saleDeedExecutionDeadline', label: 'Sale Deed Execution Deadline', type: 'text' },
    { name: 'stampDutyParty', label: 'Stamp Duty Party', type: 'text' },
    { name: 'registrationParty', label: 'Registration Charges Party', type: 'text' },
    { name: 'sellerConsentFamily', label: 'Seller Consent Family (wife/husband/sons/daughters)', type: 'text' },
    { name: 'witness1', label: 'Witness 1', type: 'text' },
    { name: 'witness2', label: 'Witness 2', type: 'text' },
  ],

  'affidavit-indemnity': [
    { name: 'byName', label: 'Affidavit By (Name)', type: 'text' },
    { name: 'inFavourOf', label: 'In Favour Of', type: 'text' },
    { name: 'deponentName', label: 'Deponent Name', type: 'text' },
    { name: 'deponentAge', label: 'Deponent Age', type: 'text' },
    { name: 'employer', label: 'Employer/Bank Name', type: 'text' },
    { name: 'premisesLocation', label: 'Premises Location', type: 'text' },
    { name: 'premisesName', label: 'Premises Name', type: 'text' },
    { name: 'premisesAddress', label: 'Premises Address', type: 'text' },
    { name: 'premisesOwner', label: 'Premises Owner', type: 'text' },
    { name: 'agreementDate', label: 'Agreement Date', type: 'text' },
    { name: 'leaveLicenseEndDate', label: 'Leave & License End Date', type: 'text' },
    { name: 'companyName', label: 'Company/Bank Name (for indemnity)', type: 'text' },
    { name: 'transferFrom', label: 'Transfer From (City)', type: 'text' },
    { name: 'transferTo', label: 'Transfer To (City)', type: 'text' },
    { name: 'indemnifiedParty', label: 'Indemnified Party', type: 'text' },
    { name: 'swornDay', label: 'Sworn Day', type: 'text' },
    { name: 'swornMonth', label: 'Sworn Month', type: 'text' },
    { name: 'swornYear', label: 'Sworn Year', type: 'text' },
    { name: 'swornBeforeDay', label: 'Sworn Before Day', type: 'text' },
    { name: 'swornBeforeMonth', label: 'Sworn Before Month', type: 'text' },
    { name: 'swornBeforeYear', label: 'Sworn Before Year', type: 'text' },
  ],
  // Add more templates as needed
};

function TypewriterHeading({
  text,
  speed = 50,
  pause = 1200,
  className = "",
}: {
  text: string;
  speed?: number;
  pause?: number;
  className?: string;
}) {
  const [displayed, setDisplayed] = useState('');
  const [index, setIndex] = useState(0);

  useEffect(() => {
    if (index < text.length) {
      const timeout = setTimeout(() => {
        setDisplayed((prev) => prev + text[index]);
        setIndex((i) => i + 1);
      }, speed);
      return () => clearTimeout(timeout);
    } else {
      const timeout = setTimeout(() => {
        setDisplayed('');
        setIndex(0);
      }, pause);
      return () => clearTimeout(timeout);
    }
  }, [index, text, speed, pause]);

  return (
    <h2 className={`text-xl font-bold mb-6 capitalize text-center text-[#14532D] min-h-[2.5em] ${className}`}>
      {displayed}
      <span className="animate-pulse text-[#14532D]">|</span>
    </h2>
  );
}

export default function TemplateForm() {
  const { type } = useParams();
  const navigate = useNavigate();
  const fields = templateFields[type as string] || [];
  const [form, setForm] = useState<Record<string, any>>({});
  const [loading, setLoading] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    const res = await fetch('http://localhost:5000/api/templates/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ type, data: form }),
    });
    const blob = await res.blob();
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${type}.pdf`;
    a.click();
    window.URL.revokeObjectURL(url);
    setLoading(false);
    navigate('/dashboard/templates');
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#D6BFAA] via-[#FFFAF0] to-[#A7F3D0] flex flex-col items-center justify-center py-10">
      <h1 className="text-4xl font-extrabold mb-8 mt-14 tracking-wide text-[#2E2E2E]"
        style={{ fontFamily: '"Playfair Display", serif' }}
      >
        Legal Document Generator
      </h1>

      <div className="bg-white/90 rounded-2xl shadow-2xl p-8 max-w-xl w-full">
        <TypewriterHeading
          text={`Fill out the form below to generate your ${type?.replace('-', ' ')} PDF.`}
        />
        <form onSubmit={handleSubmit} className="space-y-5">
          {fields.map(f => (
            <div key={f.name}>
              <label className="block mb-1 font-semibold text-[#2E2E2E]">{f.label}</label>
              <input
                name={f.name}
                type={f.type}
                required
                className="w-full border  border-gray-400  rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-[#14532D] transition"
                onChange={handleChange}
              />
            </div>
          ))}
          <button
            type="submit"
            disabled={loading}
            className=" px-6 py-3 bg-gradient-to-r from-[#D97706] to-[#F59E0B] text-white font-bold rounded-lg shadow-lg hover:shadow-xl hover:scale-105 transition-transform duration-300 ease-in-out cursor-pointer text-lg"
          >
            {loading ? 'Generating...' : 'Generate PDF'}
          </button>
        </form>
      </div>
    </div>
  );
}